### ISSUE TITLE
Provide the ability to unset env variable

### ISSUE THREAD

**Issue by bbtfr** [bkeepers/dotenv#247]
It would be really nice if we can unset a env var, here is the story:

I have a global env var http_proxy in my ~/.bash_profile, and I don't need a proxy in my rails app
I've tried to set http_proxy='', which will not work as expected, it gives me an error: Non-HTTP proxy URI

so it would be really nice if I can unset http_proxy in dotenv file, by something like `unset http_proxy`

**Comment by bkeepers** [comment]
Hey @bbtfr, thanks for the suggestion. I'll need to think a little more about the best way to do this, and if it's even in scope for what dotenv should be doing. In the mean time, could you manually delete it in your application?

```
ENV.delete("http_proxy")
```

Also, could you post the full stack trace of the error your seeing? I'm just curious if there's a way to make the code better handle an empty value.

**Comment by bbtfr** [comment]
Sorry for the delay.
Of cause we can do it programmatically, ie: `ENV.delete("http_proxy")`, and I'm doing it in this way currently.
But I just thought we might want to keep all the env vars in `.env` file, including unset an env var (or, in other words, set an env var to nil)

**Comment by bbtfr** [comment]
This is what I met:

```
1.9.3-p448 :001 > require 'open-uri'
 => true
1.9.3-p448 :002 > ENV['http_proxy']
 => "http://ucf-b2b-proxy.us.blablabla.com:80"
1.9.3-p448 :003 > open 'http://publisher.slc05hpw.blablabla.com/posts'
OpenURI::HTTPError: 502 notresolvable
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:346:in `open_http'
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:775:in `buffer_open'
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:201:in `catch'
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:677:in `open'
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:33:in `open'
  from (irb):3
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/bin/irb:12:in `<main>'
1.9.3-p448 :004 > ENV['http_proxy']="" # same as `export http_proxy=''` in .env file
 => ""
1.9.3-p448 :005 > open 'http://publisher.slc05hpw.blablabla.com/posts'
RuntimeError: Non-HTTP proxy URI:
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:249:in `open_http'
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:775:in `buffer_open'
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:201:in `catch'
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:677:in `open'
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:33:in `open'
  from (irb):5
  from /home/blablabla/.rvm/rubies/ruby-1.9.3-p448/bin/irb:12:in `<main>'
1.9.3-p448 :006 > ENV['http_proxy']=nil
 => nil
1.9.3-p448 :007 > open 'http://publisher.slc05hpw.blablabla.com/posts'
 => #<StringIO:0x00000002c3e248>
```

**Comment by bbtfr** [comment]
OK, I got your point, dotenv will not "override" env vars, so it will not override an env var to nil, aka: unset it.

**Comment by srogers** [comment]
Did this ever go anywhere? It would be convenient to be able to remove .env variables in .env.test rather than in code, precisely because these don't get checked in.
