### ISSUE TITLE
Getting problems with 2.1.1,  reverted to 2.1.0

### ISSUE THREAD

**Issue by USvER** [bkeepers/dotenv#258]
With 2.1.1 i'm getting this error:
```
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'dotenv-rails'. (Bundler::GemRequireError)
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
        from /root/dilitio/config/application.rb:7:in `<top (required)>'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:88:in `require'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:88:in `block in server'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:85:in `tap'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:85:in `server'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
        from /root/dilitio/bin/rails:9:in `require'
        from /root/dilitio/bin/rails:9:in `<top (required)>'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
        from /root/dilitio/bin/spring:13:in `require'
        from /root/dilitio/bin/spring:13:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```

With 2.1.0 everything fine! Rails 5.0

**Comment by warmwaffles** [comment]
We are running rails 5 with dotenv 2.1.1 just fine.

**Comment by bkeepers** [comment]
@USvER are you still running into this? I haven't heard any other reports, and the stack trace doesn't appear to be very helpful.

I'm going to close this, but let me know if you're still having troubles and I'll reopen it.

**Comment by USvER** [comment]
I have tried to run with 2.1.1 again and got this problem:
```
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'dotenv-rails'. (Bundler::GemRequireError)
Gem Load Error is: couldn't find HOME environment -- expanding `~'
```
I'm runing my rails using upstart (`service myapp start`), i guess that's why it does not get any HOME...
With 2.1.0 i don't get this error.

**Comment by bkeepers** [comment]
Here are the [changes between v2.1.0..v2.1.1](https://github.com/bkeepers/dotenv/compare/v2.1.0...v2.1.1). The only change that is not related to fixing rubocop style warnings is f79694002bd81c8f5b8ae3381764ade49a594cde. I don't see anything else that would cause this issue (unless the [change from `fail` to `raise`](https://github.com/bkeepers/dotenv/compare/v2.1.0...v2.1.1#diff-865ae296f689d8303a0282c995e1a1fe) would expose an error that is being swallowed in 2.1.0?).

I'm not seeing `~` anywhere in this code base (besides in tests).  Calling `expand_path` has [been around since 0.8.0](https://github.com/bkeepers/dotenv/commit/01eeb196ac33e55f21f453d05fe73272f47dfc8b).

Any other insight would be appreciated.

**Comment by candland** [comment]
I added HOME=/users/username to my monit script to fix this.
