### ISSUE TITLE
ENV Variables not loading for Podio Sinatra

### ISSUE THREAD

**Issue by rolandobrown** [bkeepers/dotenv#268]
```
Podio.setup(api_key: ENV['AI_PODIO_API_KEY'], api_secret: ENV['AI_PODIO_API_SECRET'])
Podio.client.authenticate_with_credentials(ENV['HSC_ADMIN_PODIO_ACCOUNT'], ENV['HSC_ADMIN_PODIO_PASSWORD'])
```

```
rake aborted!
Podio::BadRequestError: Sorry, you've supplied an invalid client id.
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/podio-2.0.0/lib/podio/middleware/error_response.rb:51:in `on_complete'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:56:in `call'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/podio-2.0.0/lib/podio/middleware/logger.rb:11:in `block in call'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/podio-2.0.0/lib/podio.rb:50:in `log'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/podio-2.0.0/lib/podio/client.rb:26:in `log'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/podio-2.0.0/lib/podio/middleware/logger.rb:10:in `call'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/podio-2.0.0/lib/podio/middleware/oauth2.rb:10:in `call'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/request/multipart.rb:14:in `call'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/podio-2.0.0/lib/podio/middleware/json_request.rb:17:in `call'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/podio-2.0.0/lib/podio/client.rb:60:in `authenticate_with_credentials'
/Users/rolandobrown/GitHub/projects/sw/hsc_map/models/export.rb:29:in `<top (required)>'
/Users/rolandobrown/GitHub/projects/sw/hsc_map/Rakefile:2:in `require'
/Users/rolandobrown/GitHub/projects/sw/hsc_map/Rakefile:2:in `<top (required)>'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/rolandobrown/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by squarism** [comment]
Do you have an initializer that loads Dotenv?  If this is the complete initialization of your app, you need to `Dotenv.load`.

**Comment by rolandobrown** [comment]
@squarism Thanks!
