### ISSUE TITLE
Skip over non-envvar lines

### ISSUE THREAD

**Issue by sloria** [bkeepers/dotenv#285]
`.env` files may contain lines that don't set environment variables. For example, I use [autoenv](https://github.com/kennethreitz/autoenv) in order to automatically activate the current project's Python virtual environment. I also set per-project aliases in `.env`. 

`dotenv` raises an error when it encounters lines that don't set envvars:

```
/usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv/parser.rb:63:in `parse_line': Line "source activate osf" doesn't match format (Dotenv::FormatError)
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv/parser.rb:47:in `block in call'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv/parser.rb:46:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv/parser.rb:46:in `call'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv/parser.rb:36:in `call'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv/environment.rb:13:in `load'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv/environment.rb:9:in `initialize'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:15:in `new'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:15:in `block (2 levels) in load'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:59:in `ignoring_nonexistent_files'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:14:in `block in load'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:46:in `block in with'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:45:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:45:in `reduce'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:45:in `with'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:13:in `load'
        from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.2.0/lib/docker-sync/sync_manager.rb:19:in `initialize'
        from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.2.0/tasks/sync/sync.thor:30:in `new'
        from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.2.0/tasks/sync/sync.thor:30:in `start'
        from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.2.0/bin/docker-sync:14:in `<top (required)>'
        from /usr/local/bin/docker-sync:22:in `load'
        from /usr/local/bin/docker-sync:22:in `<main>'
```

Would the maintainer(s) be open to skipping these lines rather than raising an error?

**Comment by sloria** [comment]
For what it's worth, both Foreman (https://github.com/ddollar/foreman/blob/5f5502efed74c68f5cf381d38b2ad497676837ec/lib/foreman/env.rb#L8-L18) and honcho (https://github.com/nickstenning/honcho/blob/6bad0da2806231ac8f3a07d76847a566b96745e6/honcho/environ.py#L73-L99) implement the suggested behavior (skipping lines that don't set envvars).

**Comment by sloria** [comment]
Is this something the maintainers would be willing to change? If so, I could work on a PR.

**Comment by bkeepers** [comment]
Hey @sloria, thanks for the suggestion. I'm not opposed. My only concern is that it might lead to unexpected behavior for people that don't realize they have the format wrong, but I think I'm ok with that.

Feel free to open a PR!
