### ISSUE TITLE
Gem Load Error is: undefined local variable or method `dotenv_files'

### ISSUE THREAD

**Issue by heaven** [bkeepers/dotenv#297]
Getting this with 2.2.0, 2.1.2 does work.

```
runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'dotenv/rails-now'. (Bundler::GemRequireError)
Gem Load Error is: undefined local variable or method `dotenv_files' for #<Dotenv::Railtie:0x007fd3f94eac30>
Backtrace for gem load error is:
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/dotenv-rails-2.2.0/lib/dotenv/rails.rb:38:in `load'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/dotenv-rails-2.2.0/lib/dotenv/rails.rb:51:in `load'
```

**Comment by n0nick** [comment]
FWIW a hacky way to avoid this error is by adding the following to `config/application.rb` (before the `Bundler.require` call):

```ruby
module Dotenv
  class Railtie < Rails::Railtie
    def dotenv_files; end
  end
end
```

Note that the method is empty but it later gets overridden and the gem's behavior remains unaffected. I was not able to pinpoint what exactly causes the issue with this version.

**Comment by softmonkeyjapan** [comment]
I'm having a similar issue on my staging server. The server is using the following:
```
Ruby 2.2.5
Rails 5.1.1
dotenv 2.2.1
unicorn 5.3.0
```
When starting my unicorn server, the log shows the following error message:
```
I, [2017-07-12T00:01:23.110852 #30507]  INFO -- : Refreshing Gem list
E, [2017-07-12T00:01:23.132283 #30495] ERROR -- : There was an error while trying to load the gem 'dotenv/rails-now'.
Gem Load Error is: couldn't find HOME environment -- expanding `~'
Backtrace for gem load error is:
/usr/local/rvm/gems/ruby-2.2.5/gems/spring-2.0.2/lib/spring/commands.rb:28:in `expand_path'
/usr/local/rvm/gems/ruby-2.2.5/gems/spring-2.0.2/lib/spring/commands.rb:28:in `<module:Spring>'
/usr/local/rvm/gems/ruby-2.2.5/gems/spring-2.0.2/lib/spring/commands.rb:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/gems/dotenv-rails-2.2.1/lib/dotenv/rails.rb:20:in `require'
/usr/local/rvm/gems/ruby-2.2.5/gems/dotenv-rails-2.2.1/lib/dotenv/rails.rb:20:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/gems/dotenv-rails-2.2.1/lib/dotenv/rails-now.rb:9:in `require'
/usr/local/rvm/gems/ruby-2.2.5/gems/dotenv-rails-2.2.1/lib/dotenv/rails-now.rb:9:in `<top (required)>'
```

However, when I manually downgrade `dotenv` to version `2.1.x`, everything seems to work as expected. The problem is that I cannot use `dotenv 2.1.x` as `Rails 5.1` is not supported on that version.

Any of you have an idea of why this is happening?

**Comment by n0nick** [comment]
Can we please reopen this? This bug was reported for version 2.2.1 which is the latest, so I think it's still relevant.

**Comment by jaydorsey** [comment]
I'm running into a similar error w/ 2.2.1 (latest), minus the `rails-now` part.

I'm deploying to an elastic beanstalk environment on AWS, and the error occurs when running a `bundle exec` command during deployment. There may be other issues at hand (permissions, context, AWS specific things, etc.) but I do seem to be able to reproduce this error (at least with my production code). Happy to provide more detail if necessary.

Things that didn't work:

- Setting the DISABLE_SPRING environment variable (spring isn't even bundled or on the system)
- Including an empty `.env` file
- Removing `BUNDLE_WITHOUT`

Things that do work:

- SSH'ing into the instance and running the command manually
- Downgrading to 2.1.1
- Prepending `HOME=/var/app/ondeck` to my `bundle exec rake` command (this is what I'm using to deploy)

Assuming it's got something to do with the scripts running as root and not having a HOME environment variable set (just like the error message says)

Environment:

Ruby 2.3.4
Rails 4.2.7.1
Bundler 1.15.4
Rake 12.1.0

Backtrace

```
rake aborted!
  Bundler::GemRequireError: There was an error while trying to load the gem 'dotenv-rails'.
  Gem Load Error is: couldn't find HOME environment -- expanding `~'
  Backtrace for gem load error is:
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/spring-2.0.2/lib/spring/commands.rb:28:in `expand_path'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/spring-2.0.2/lib/spring/commands.rb:28:in `<module:Spring>'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/spring-2.0.2/lib/spring/commands.rb:4:in `<top (required)>'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/dotenv-rails-2.2.1/lib/dotenv/rails.rb:20:in `require'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/dotenv-rails-2.2.1/lib/dotenv/rails.rb:20:in `<top (required)>'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/dotenv-rails-2.2.1/lib/dotenv-rails.rb:1:in `require'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/dotenv-rails-2.2.1/lib/dotenv-rails.rb:1:in `<top (required)>'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `require'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `each'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `block in require'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `each'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `require'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler.rb:108:in `require'
  /var/app/ondeck/config/application.rb:15:in `<top (required)>'
  /var/app/ondeck/Rakefile:4:in `require'
  /var/app/ondeck/Rakefile:4:in `<top (required)>'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/rake_module.rb:29:in `load'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/rake_module.rb:29:in `load_rakefile'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:688:in `raw_load_rakefile'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:97:in `block in load_rakefile'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:96:in `load_rakefile'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:80:in `block in run'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:78:in `run'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<top (required)>'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
  /opt/rubies/ruby-2.3.4/bin/bundle:23:in `load'
  /opt/rubies/ruby-2.3.4/bin/bundle:23:in `<main>'
  Bundler Error Backtrace:
  /var/app/ondeck/config/application.rb:15:in `<top (required)>'
  /var/app/ondeck/Rakefile:4:in `require'
  /var/app/ondeck/Rakefile:4:in `<top (required)>'
  /var/app/ondeck/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
  /opt/rubies/ruby-2.3.4/bin/bundle:23:in `load'
  /opt/rubies/ruby-2.3.4/bin/bundle:23:in `<main>'
  ArgumentError: couldn't find HOME environment -- expanding `~'
```

It looks like it is related to the commit noted above, because by switching from loading `watcher` to `commands`, [this line](https://github.com/rails/spring/blob/master/lib/spring/commands.rb#L28) was introduced.

I'm chalking it up to an environment issue created by not having that HOME path set, because `File.expand_path` dies when `HOME` isn't set. `watcher` didn't have any `File.expand_path` calls.

Rescuing `Bundler::GemRequireError` might be a reasonable fix (in addition to `LoadError`, [here](https://github.com/thewatts/dotenv/blob/master/lib/dotenv/rails.rb#L12)

If @bkeepers is amenable I can fork, test, and do a PR if that resolves it.

**Comment by mokolabs** [comment]
I just ran into this bug, FWIW.

**Comment by heaven** [comment]
Just wanted to warn anyone about this hack:
```ruby
module Dotenv
  class Railtie < Rails::Railtie
    def dotenv_files; end
  end
end
```

Don't use it as it will mess your environment.

**Comment by zx1986** [comment]
Gem Load Error is: non-absolute home

```
Bundler Error Backtrace:
/usr/local/rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:85:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/home/app/config/application.rb:8:in `<top (required)>'
/home/app/Rakefile:4:in `require'
/home/app/Rakefile:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
ArgumentError: non-absolute home
/usr/local/rvm/gems/ruby-2.3.1/gems/spring-2.0.2/lib/spring/commands.rb:28:in `expand_path'
/usr/local/rvm/gems/ruby-2.3.1/gems/spring-2.0.2/lib/spring/commands.rb:28:in `<module:Spring>'
/usr/local/rvm/gems/ruby-2.3.1/gems/spring-2.0.2/lib/spring/commands.rb:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/dotenv-rails-2.2.1/lib/dotenv/rails.rb:20:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/dotenv-rails-2.2.1/lib/dotenv/rails.rb:20:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/dotenv-rails-2.2.1/lib/dotenv-rails.rb:1:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/dotenv-rails-2.2.1/lib/dotenv-rails.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/home/app/config/application.rb:8:in `<top (required)>'
```

```
Ruby 2.3.1p112
Rails 4.2.3
rake, version 12.0.0
Bundler version 1.12.5
```
