### ISSUE TITLE
 dotenv-rails 2.2.1 with bundler 1.16.0 crashes Rails 5.2.0.beta2

### ISSUE THREAD

**Issue by mdesantis** [bkeepers/dotenv#321]
Adding dotenv-rails 2.2.1 to a brand new Rails 5.2.0.beta2 project breaks everything with this error:

```
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/constants.rb:4: warning: already initialized constant Bundler::WINDOWS
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/constants.rb:4: warning: previous definition of WINDOWS was here
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/constants.rb:5: warning: already initialized constant Bundler::FREEBSD
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/constants.rb:5: warning: previous definition of FREEBSD was here
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/constants.rb:6: warning: already initialized constant Bundler::NULL
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/constants.rb:6: warning: previous definition of NULL was here
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/rubygems_integration.rb:10: warning: already initialized constant Bundler::RubygemsIntegration::EXT_LOCK
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/rubygems_integration.rb:12: warning: previous definition of EXT_LOCK was here
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/current_ruby.rb:12: warning: already initialized constant Bundler::CurrentRuby::KNOWN_MINOR_VERSIONS
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/current_ruby.rb:12: warning: previous definition of KNOWN_MINOR_VERSIONS was here
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/current_ruby.rb:23: warning: already initialized constant Bundler::CurrentRuby::KNOWN_MAJOR_VERSIONS
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/current_ruby.rb:23: warning: previous definition of KNOWN_MAJOR_VERSIONS was here
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/current_ruby.rb:25: warning: already initialized constant Bundler::CurrentRuby::KNOWN_PLATFORMS
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/current_ruby.rb:25: warning: previous definition of KNOWN_PLATFORMS was here
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/fileutils/lib/fileutils.rb:1186: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/vendor/fileutils/lib/fileutils.rb:1186: warning: previous definition of S_IF_DOOR was here
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/fileutils/lib/fileutils.rb:1444: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/vendor/fileutils/lib/fileutils.rb:1444: warning: previous definition of DIRECTORY_TERM was here
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/fileutils/lib/fileutils.rb:1446: warning: already initialized constant Bundler::FileUtils::Entry_::SYSCASE
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/vendor/fileutils/lib/fileutils.rb:1446: warning: previous definition of SYSCASE was here
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/fileutils/lib/fileutils.rb:1499: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/vendor/fileutils/lib/fileutils.rb:1499: warning: previous definition of OPT_TABLE was here
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/fileutils/lib/fileutils.rb:1553: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/vendor/fileutils/lib/fileutils.rb:1553: warning: previous definition of LOW_METHODS was here
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/fileutils/lib/fileutils.rb:1560: warning: already initialized constant Bundler::FileUtils::METHODS
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/vendor/fileutils/lib/fileutils.rb:1560: warning: previous definition of METHODS was here
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'dotenv-rails'. (Bundler::GemRequireError)
Gem Load Error is: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
Backtrace for gem load error is:
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/errors.rb:9:in `status_code'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/errors.rb:20:in `<class:GemfileError>'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/errors.rb:20:in `<module:Bundler>'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/errors.rb:3:in `<main>'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler.rb:10:in `<main>'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/setup.rb:6:in `<main>'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/commands.rb:33:in `<module:Spring>'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/commands.rb:4:in `<main>'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/dotenv-rails-2.2.1/lib/dotenv/rails.rb:20:in `<main>'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/dotenv-rails-2.2.1/lib/dotenv-rails.rb:1:in `<main>'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `each'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `block in require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `each'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler.rb:114:in `require'
/home/user/app/config/application.rb:7:in `<main>'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:145:in `block in perform'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:142:in `tap'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:142:in `perform'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/command/base.rb:65:in `perform'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/command.rb:46:in `invoke'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands.rb:18:in `<main>'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
/home/user/app/bin/rails:9:in `<top (required)>'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:70:in `require'
/home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:70:in `require'
/home/user/app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Bundler Error Backtrace:
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:80:in `block (2 levels) in require'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `each'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `block in require'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `each'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `require'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/bundler.rb:114:in `require'
	from /home/user/app/config/application.rb:7:in `<main>'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:142:in `tap'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/command/base.rb:65:in `perform'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/command.rb:46:in `invoke'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.2.0.beta2/lib/rails/commands.rb:18:in `<main>'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
	from /home/user/app/bin/rails:9:in `<top (required)>'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	from /home/user/.asdf/installs/ruby/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	from /home/user/app/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

### Steps to reproduce

- Create a new Rails 5.2.0.beta2 project
- Add `gem 'dotenv-rails'` to `group :development, :test`
- Run `bundle install`
- Run `rails console`

### env files contents

None

### System configuration

**dotenv-rails version**: 2.2.1

**dotenv version**: 2.2.1

**Rails version**: 5.2.0.beta2

**Bundler version**: 1.16.0

**Ruby version**: 2.4.2

**Comment by pedantic-git** [comment]
I see bootsnap in your trace. I had the same problem until I ditched bootsnap.

**Comment by mattbrictson** [comment]
Downgrading to rubygems 2.7.4 with `gem update --system 2.7.4` fixed it for me.

The problem seems be related to the fact that the rubygems 2.7.5+ comes with its own copy of bundler. If you `gem install bundler` using rubygems 2.7.5+, then you somehow end up with two copies of bundler. Perhaps this confuses bootsnap into loading bundler twice.

**Comment by mattbrictson** [comment]
This _might_ be another manifestation of this bug: https://github.com/Shopify/bootsnap/issues/103

**Comment by mattbrictson** [comment]
I am pretty sure this is not the fault of `dotenv`. This is the root cause: https://github.com/Shopify/bootsnap/issues/134

**Comment by wellington1993** [comment]
Hi, I removed `require 'bootsnap/setup'` from `boot.rb` and worked for me.

**Comment by jonmagic** [comment]
I believe this is resolved.
