### ISSUE TITLE
Dotenv-rails to a Rails 5.1.5 breaks with this error

### ISSUE THREAD

**Issue by zismailov** [bkeepers/dotenv#324]
Adding dotenv-rails  to a  Rails 5.1.5 project breaks everything with this error:

```
Traceback (most recent call last):
	19: from bin/rails:9:in `<main>'
	18: from bin/rails:9:in `require'
	17: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
	16: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
	15: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
	14: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	13: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	12: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	11: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `perform'
	10: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `tap'
	 9: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:133:in `block in perform'
	 8: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:133:in `require'
	 7: from /Users/guest/Project/GitHub/test/config/application.rb:7:in `<top (required)>'
	 6: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
	 5: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
	 4: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
	 3: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
	 2: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
	 1: from /Users/guest/.rvm/gems/ruby-2.5.0@test/gems/bundler-1.16.1/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'dotenv-rails'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Rake::DSL
Backtrace for gem load error is:
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/dotenv-0.7.0/lib/dotenv/railtie.rb:5:in `<class:Railtie>'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/dotenv-0.7.0/lib/dotenv/railtie.rb:4:in `<module:Dotenv>'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/dotenv-0.7.0/lib/dotenv/railtie.rb:3:in `<top (required)>'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/dotenv-rails-0.7.0/lib/dotenv-rails.rb:1:in `<top (required)>'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/Users/guest/Project/GitHub/test/config/application.rb:7:in `<top (required)>'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:133:in `require'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:133:in `block in perform'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `tap'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `perform'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
/Users/guest/.rvm/gems/ruby-2.5.0@test/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:9:in `require'
bin/rails:9:in `<main>'
Bundler Error Backtrace:
```

### Steps to reproduce
Create a new Rails 5.1.5 project
Add gem 'dotenv-rails' to group :development, :test
Run bundle install
Run rails server

### env files contents
None

### System configuration
**Dotenv**: 0.7.0

**Rails**: 5.1.5

**Bundler**: 1.16.1

**Ruby**:  2.5.0

**Comment by stephenhmarsh** [comment]
The problem is coming from:
`dotenv-0.7.0/lib/dotenv/railtie.rb`

```
require 'dotenv'

module Dotenv
  class Railtie < Rails::Railtie
    include Rake::DSL if defined?(Rake)
    

    rake_tasks do
      desc 'Load environment settings from .env'
      task :dotenv do
        Dotenv.load ".env.#{Rails.env}", '.env'
      end
    end
  end
end

Dotenv.load ".env.#{Rails.env}", '.env'

```

I'm seeing that `Rake` is defined at this point, but its only constants are:

```
[6] pry(Dotenv::Railtie)> Rake.constants
=> [:FileList, :Cloneable, :FileUtilsExt]
```

No `::DSL` to be found...

However I don't see anything in this file that actually **needs** `Rake::DSL` ???

Because `rake_tasks` actually comes from Railtie:
https://github.com/rails/rails/blob/fa8602656edbf879430fffefc5efa11d253da003/railties/lib/rails/railtie.rb#L135

In fact if I comment out `include Rake::DSL if defined?(Rake)`, then everything works again.

**Comment by stephenhmarsh** [comment]
**Update:**

In my case, the error was caused by someone locking the foreman gem to an older version, which locked dotenv to a **much** older version.

When I set my dependency for `dotenv-rails` to `~> 2.2.1` in my Gemfile, I was able to get this error:

```
Bundler could not find compatible versions for gem "dotenv":
  In snapshot (Gemfile.lock):
    dotenv (= 0.7.0)

  In Gemfile:
    dotenv-rails (~> 2.2.1) was resolved to 2.2.1, which depends on
      dotenv (= 2.2.1)

    foreman (~> 0.64.0) was resolved to 0.64.0, which depends on
      dotenv (~> 0.7.0)
```

@zismailov  I see you also have this very old version of dotenv-rails, so if you can find what is preventing it from being updated, you will probably not have this bug!

**Comment by zismailov** [comment]
@stephenhmarsh I updated **dotenv-rails** as **'dotenv-rails', '~> 2.1', '>= 2.1.1'**, everything worked!

**Comment by max-underthesun** [comment]
got the same error and solve it the very same way - updated 'dotenv-rails', which was locked by 'foreman' ))
