### ISSUE TITLE
v2.3.0 breaks rake v12.3.1 on ruby v2.2.4 and rails v4.2.10

### ISSUE THREAD

**Issue by baburdick** [bkeepers/dotenv#334]
### Steps to reproduce
Run `rake -T` with dotenv v2.3.0, rake v12.3.1, ruby v2.2.4, and rails v4.2.10.

### Expected behavior
Rake should work properly like it does with dotenv v2.2.2.

### Actual behavior
With rake v12.3.1 and ruby v2.2.4:
```
$ rake -T
rake aborted!
ArgumentError: wrong number of arguments (1 for 2)
~/.rvm/gems/ruby-2.2.4@my_app/gems/dotenv-2.3.0/lib/dotenv/environment.rb:7:in `initialize'
~/Code/my_app/config/application.rb:22:in `new'
~/Code/my_app/config/application.rb:22:in `<top (required)>'
~/Code/my_app/Rakefile:4:in `require'
~/Code/my_app/Rakefile:4:in `<top (required)>'
~/.rvm/gems/ruby-2.2.4@my_app/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
~/.rvm/gems/ruby-2.2.4@my_app/bin/ruby_executable_hooks:15:in `eval'
~/.rvm/gems/ruby-2.2.4@my_app/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```
My config/application.rb, lines 14-23:
```ruby
# Set SECRET_KEY_BASE for console and the runner:
if ENV["SECRET_KEY_BASE"].nil?
  dot_env_file = File.expand_path('../../.env', __FILE__)

  if %w[staging production].include? ENV["RACK_ENV"]
    dot_env_file << "." << ENV["RACK_ENV"]
  end

  ENV.update Dotenv::Environment.new(dot_env_file)
end
```

### System configuration
**dotenv version**: v2.3.0

**Rails version**: v4.2.10

**Ruby version**: v2.2.4

**Comment by baburdick** [comment]
Hmm. Looks like the environment is now initialized with 2 args instead of one. And it looks like my custom addition to `config/application.rb` is what must change to accommodate this.

**Comment by baburdick** [comment]
Yep. Updating my custom code like so fixes the issue:
```diff
- ENV.update Dotenv::Environment.new(dot_env_file)
+ ENV.update Dotenv::Environment.new(dot_env_file, true)
```

**Comment by baburdick** [comment]
This can be closed. I'll leave it open for a brief period in case anyone else stumbles across this issue by mucking around with non-public APIs. Maintainers: feel free to close this sooner.

**Comment by JessRudder** [comment]
@baburdick thanks for both the great write up of the initial problem as well as an update when you found the solution.  This will be very helpful for other intrepid developers experiencing similar issues.

**Comment by chrise86** [comment]
I'm getting this issue when trying to start the server using [Invoker](http://invoker.codemancers.com/). Not using any custom loading.

Backtrace:
```
Traceback (most recent call last):
	16: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/bin/invoker:23:in `<main>'
	15: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/bin/invoker:23:in `load'
	14: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/invoker-1.5.6/bin/invoker:7:in `<top (required)>'
	13: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/invoker-1.5.6/lib/invoker/cli.rb:12:in `start'
	12: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	11: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	10: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	 9: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	 8: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/invoker-1.5.6/lib/invoker/cli.rb:62:in `start'
	 7: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/invoker-1.5.6/lib/invoker/commander.rb:40:in `start_manager'
	 6: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/invoker-1.5.6/lib/invoker/commander.rb:40:in `each'
	 5: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/invoker-1.5.6/lib/invoker/commander.rb:41:in `block in start_manager'
	 4: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/invoker-1.5.6/lib/invoker/process_manager.rb:19:in `start_process'
	 3: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/invoker-1.5.6/lib/invoker/process_manager.rb:189:in `run_command'
	 2: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/invoker-1.5.6/lib/invoker/process_manager.rb:101:in `load_env'
	 1: from /Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/invoker-1.5.6/lib/invoker/process_manager.rb:101:in `new'
/Users/chrisedwards/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/dotenv-2.4.0/lib/dotenv/environment.rb:7:in `initialize': wrong number of arguments (given 1, expected 2) (ArgumentError)
```

`/Users/chrisedwards/.asdf/installs/ruby/2.5.0/bin/invoker` contains the following:
```
#!/Users/chrisedwards/.asdf/installs/ruby/2.5.0/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'invoker' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('invoker', 'invoker', version)
else
gem "invoker", version
load Gem.bin_path("invoker", "invoker", version)
end
```

line 23 being:

```
load Gem.activate_bin_path('invoker', 'invoker', version)
```

**Comment by chrise86** [comment]
Looks like an [Invoker issue](https://github.com/code-mancers/invoker/blob/cf0fc64c1a8e64bed3811e995c2ac605498925d9/lib/invoker/process_manager.rb#L100)
